image: trainiteu/gitpod-cpp

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Conan update
    before: |
      sudo pip3 install -U conan
      gp sync-done conan-update
      exit
  - name: gcc-11
    init: |
      gp sync-await conan-update
      mkdir -p build/GCC-11 && cd build/GCC-11
      conan install ../.. -pr gcc11 -s compiler.cppstd=20 -e mp-units:CONAN_RUN_TESTS=True -o build_docs=False -b outdated
      conan install ../.. -pr gcc11 -s compiler.cppstd=20 -e mp-units:CONAN_RUN_TESTS=True -o build_docs=False -b outdated -s build_type=Debug
      cmake ../.. --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_C_COMPILER=/usr/bin/gcc-11 -DCMAKE_CXX_COMPILER=/usr/bin/g++-11
      cmake --build . --config Release
      cmake --build . --config Debug
      ctest -C Release
      ctest -C Debug
  - name: clang-13
    init: |
      gp sync-await conan-update
      mkdir -p build/Clang-13 && cd build/Clang-13
      conan install ../.. -pr clang13 -s compiler.cppstd=20 -e mp-units:CONAN_RUN_TESTS=True -o build_docs=False -b outdated
      conan install ../.. -pr clang13 -s compiler.cppstd=20 -e mp-units:CONAN_RUN_TESTS=True -o build_docs=False -b outdated -s build_type=Debug
      cmake ../.. --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_C_COMPILER=/bin/clang-13 -DCMAKE_CXX_COMPILER=/bin/clang++-13
      cmake --build . --config Release
      cmake --build . --config Debug
      ctest -C Release
      ctest -C Debug

vscode:
  extensions:
    - twxs.cmake
    - ms-vscode.cmake-tools
    - streetsidesoftware.code-spell-checker
    - vivaxy.vscode-conventional-commits
    - github.vscode-pull-request-github
    - lextudio.restructuredtext
