image: trainiteu/gitpod-cpp

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Conan update
    before: |
      sudo pip3 install -U conan
      gp sync-done conan-update
  - name: gcc-11 Release
    init: |
      gp sync-await conan-update
      mkdir -p build/GCC-11 && cd build/GCC-11
      conan install ../.. -pr gcc11 -s compiler.cppstd=20 -e mp-units:CONAN_RUN_TESTS=True -o build_docs=False -b outdated
      conan build ../..
  - name: gcc-11 Debug
    init: |
      gp sync-await conan-update
      mkdir -p build/GCC-11 && cd build/GCC-11
      conan install ../.. -pr gcc11 -s compiler.cppstd=20 -s build_type=Debug -e mp-units:CONAN_RUN_TESTS=True -o build_docs=False -b outdated
      conan build ../..
  - name: clang-13 Release
    init: |
      gp sync-await conan-update
      mkdir -p build/Clang-13 && cd build/Clang-13
      conan install ../.. -pr clang13 -s compiler.cppstd=20 -e mp-units:CONAN_RUN_TESTS=True -o build_docs=False -b outdated
      conan build ../..
  - name: clang-13 Debug
    init: |
      gp sync-await conan-update
      mkdir -p build/Clang-13 && cd build/Clang-13
      conan install ../.. -pr clang13 -s compiler.cppstd=20 -s build_type=Debug -e mp-units:CONAN_RUN_TESTS=True -o build_docs=False -b outdated
      conan build ../..

vscode:
  extensions:
    - twxs.cmake
    - ms-vscode.cmake-tools
    - streetsidesoftware.code-spell-checker
    - vivaxy.vscode-conventional-commits
    - github.vscode-pull-request-github
    - lextudio.restructuredtext
