default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  # - repo: https://github.com/pocc/pre-commit-hooks
  #   rev: v1.3.5
  #   hooks:
  #     - id: clang-format
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: ["cmakelang[YAML]"]
      # - id: cmake-lint
      #   additional_dependencies: ["cmakelang"]
      #   exclude: "cmake/.*"
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black, --multi-line, "3"]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
