# Project information
site_name: "The mp-units library"
site_description: "A Physical Quantities and Units library for C++"
site_url: https://mpusz.github.io/mp-units
site_author: "mp-units Team"

# Repository
repo_url: https://github.com/mpusz/mp-units

# Copyright
copyright: Copyright &copy; 2018-2023 Mateusz Pusz

# Configuration
theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    # - navigation.tabs
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra:
  version:
    provider: mike

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting_started/introduction.md
      - Code Example: getting_started/code_example.md
      - Quick Start: getting_started/quick_start.md
      - Installation and Usage: getting_started/installation_and_usage.md
      - FAQ: getting_started/faq.md
  - User's Guide:
      - Terms and Definitions: users_guide/terms_and_definitions.md
      - Systems of Quantities: users_guide/systems_of_quantities.md
      - Systems of Units: users_guide/systems_of_units.md
      - Value Conversions: users_guide/value_conversions.md
      - Simple and Typed Quantities: users_guide/simple_and_typed_quantities.md
      - Basic Concepts: users_guide/basic_concepts.md
  - Library Reference:
      - Core Library: library_reference/core_library.md
  - Appendix:
      - Glossary: appendix/glossary.md
      - Release Notes: appendix/release_notes.md
