# The MIT License (MIT)
#
# Copyright (c) 2018 Mateusz Pusz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Documentation

on:
  push:
    paths:
      - ".github/workflows/documentation.yml"
      - "docs/**"
      - "src/**"
      - "example/**"
  pull_request:
    paths:
      - ".github/workflows/documentation.yml"
      - "docs/**"
      - "src/**"
      - "example/**"
jobs:
  docs:
    name: Generate documentation
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-10
      CXX: g++-10
      CMAKE_GENERATOR: Ninja
      CONAN_CMAKE_GENERATOR: Ninja
      OS: ubuntu-22.04
      BUILD_TYPE: Debug
      COMPILER_TYPE: GCC
      COMPILER_VERSION: 10
      STDLIB: libstdc++11
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Cache Conan data
        uses: actions/cache@v3
        env:
          cache-name: cache-conan-data
        with:
          path: ~/.conan2/p
          key: build-${{ matrix.os }}-$BUILD_TYPE-$COMPILER_TYPE-$COMPILER_VERSION-$STDLIB-docs
          restore-keys: |
            build-${{ matrix.os }}-$BUILD_TYPE-$COMPILER_TYPE-$COMPILER_VERSION-$STDLIB
            build-${{ matrix.os }}-$BUILD_TYPE-$COMPILER_TYPE-$COMPILER_VERSION-
            build-${{ matrix.os }}-$BUILD_TYPE-$COMPILER_TYPE-
            build-${{ matrix.os }}-$BUILD_TYPE-
            build-${{ matrix.os }}-
      - name: Install Ninja
        run: |
          sudo apt install -y ninja-build
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install Python dependencies
        run: |
          pip install -Ur docs/requirements.txt
      - name: Install Conan
        run: |
          pip install -U conan
      - name: Configure Conan
        run: |
          conan profile detect --force
          conan remote add artifactory https://mpusz.jfrog.io/artifactory/api/conan/conan-oss
      - name: Install Conan dependencies
        run: |
          conan install . -s compiler.cppstd=20 -s compiler.libcxx=$STDLIB -c user.build:all=True -c tools.cmake.cmaketoolchain:generator="Ninja Multi-Config" -b missing
      - name: Configure CMake
        run: |
          cmake --preset conan-default
      - name: Generate documentation
        run: |
          cmake --build --preset conan-release --target documentation
      - name: Deploy documentation
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/sphinx
